name: Assign Issue
on:
  issue_comment:
jobs:
  assign:
    runs-on: ubuntu-latest
    name: Assign Issue
    steps:
      - run: |
          BODY="$(jq '.comment.body' $GITHUB_EVENT_PATH)"
          ISSUE_NUMBER="$(jq '.issue.number' $GITHUB_EVENT_PATH)"
          LOGIN="$(jq '.comment.user.login' $GITHUB_EVENT_PATH | tr -d \")"
          if [[ $BODY == *".assign"* ]]; then
            echo "Assigning issue $ISSUE_NUMBER to $LOGIN"
            echo "Using the link: https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/assignees"
            curl --request POST \
              --url https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/assignees \
              --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
              --header 'content-type: application/json' \
              --data '{"assignees":["'"$LOGIN"'"]}' \
              --fail
          fi
        shell: bash