name: Format Repositories
on:
  push:
    branches: [ master ]
jobs:
  format_repositories:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
        with:
          path: csharpier
      -
        uses: actions/checkout@v2
        with:
          repository: belav/csharpier-repos
          path: csharpier-repos
      -
        run: dotnet build csharpier/Src/CSharpier/CSharpier.csproj -c release
      -
        run: csharpier/Src/CSharpier/bin/Release/net5.0/dotnet-csharpier.exe csharpier-repos/dotnet-format
