name: Publish Playground
on:
  push:
    branches: [ master ]

defaults:
  run:
    working-directory: CSharpier/CSharpier.Playground

jobs:
  build:
    runs-on: ubuntu-latest
    name: .Net 5.0 Publish
    steps:
      - 
        uses: actions/checkout@v2
      - 
        run: dotnet publish -c release --output ../../publish
      -
        working-directory: prettier-plugin-csharpier
        run: npm install && npm run build
      -
        working-directory: prettier-plugin-csharpier
        run: cp -r ./dist ../publish/Prettier
      -
        working-directory: publish/Prettier
        run: npm install
      -
        run: mkdir offline && touch offline/app_offline.htm
      - 
        name: Upload app_offline.htm
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ftp://${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "CSharpier/CSharpier.Playground/offline"
          remoteDir: "/csharpier_bntstudios_com"
      #will this clean files? https://github.com/SamKirkland/FTP-Deploy-Action it sounds like it, it could exclude app_data and app_offline, and I could delete those later
      # this may be better because port isn't separate https://github.com/marketplace/actions/simple-ftp-deploy
      - 
        name: FTP Deploy
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
        with:
          ftp_host: ${{ secrets.FTP_HOST }}
          ftp_username: ${{ secrets.FTP_USERNAME }}
          ftp_password: ${{ secrets.FTP_PASSWORD }}
          local_source_dir: "publish"
          dist_target_dir: "/csharpier_bntstudios_com"
          delete: "true"
          exclude: "'App_Data' 'app_offline.htm'"
          other_flags: "-p"
      - 
        name: Delete app_offline.htm
        uses: StephanThierry/ftp-delete-action@releases/v1
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remoteFiles: "app_offline.htm"
          workingDir: "/csharpier_bntstudios_com"