name: Validate PR
on:
  pull_request:
    branches: [ master ]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - uses: actions/checkout@v2
      - run: dotnet test Src/CSharpier.Tests/CSharpier.Tests.csproj -c release
#  check_formatting:
#    runs-on: ubuntu-latest
#    name: Check Formatting
#    steps:
#      - uses: actions/checkout@v2
#      - run: |
#          dotnet tool restore
#          dotnet csharpier --check
